stages:
  - dockerhub_login
  - build
  - syntax
  - tag
  - push
  - cleanup


dockerhub_login:
  stage: dockerhub_login
  script:
    - docker login -u ${DOCKERHUB_LOGIN} -p ${DOCKERHUB_PASSWORD}

build:
  stage: build
  script:
    - docker build . | tee /tmp/docker_build_${CI_PIPELINE_ID}.txt

syntax:
  stage: syntax
  script:
    # XXX parametrize image tag
    - >
      docker run --rm k8sprayorg/ansible:2.3.0.0 'ansible-playbook --syntax-check `ls /opt/playbooks/workflow/*.yml | grep -v requirements.yml`'

tag:
  stage: tag
  script:
    - export IMAGE_ID=`awk '/Successfully built/ {print $3}' /tmp/docker_build_${CI_PIPELINE_ID}.txt`
    - docker tag ${IMAGE_ID} k8sprayorg/ansible:2.3.0.0

push:
  stage: push
  script:
    - docker push k8sprayorg/ansible:2.3.0.0

cleanup:
  stage: cleanup
  script:
    - rm /tmp/docker_build_${CI_PIPELINE_ID}.txt
