stages:
  - dockerhub_login
  - build
  - syntax
  - tag
  - push
  - workflow_test
  - cleanup


dockerhub_login:
  only:
    - pushes
    - triggers
    - schedules
  stage: dockerhub_login
  script:
    - docker login -u ${DOCKERHUB_LOGIN} -p ${DOCKERHUB_PASSWORD}

build:
  only:
    - pushes
    - triggers
    - schedules
  stage: build
  script:
    - docker build . | tee /tmp/docker_build_${CI_PIPELINE_ID}.txt

syntax:
  only:
    - pushes
    - triggers
    - schedules
  stage: syntax
  script:
    # XXX parametrize image tag
    - >
      docker run --rm k8sprayorg/ansible:2.3.0.0 'ansible-playbook --syntax-check `ls /opt/playbooks/workflow/*.yml | grep -v requirements.yml`'

tag:
  only:
    - pushes
    - triggers
    - schedules
  stage: tag
  script:
    - export IMAGE_ID=`awk '/Successfully built/ {print $3}' /tmp/docker_build_${CI_PIPELINE_ID}.txt`
    - docker tag ${IMAGE_ID} k8sprayorg/ansible:2.3.0.0

push:
  only:
    - pushes
    - triggers
    - schedules
  stage: push
  script:
    - docker push k8sprayorg/ansible:2.3.0.0

worklow_test:
  only:
    - pushes
    - triggers
    - schedules
  stage: workflow_test
  script:
    - export CI_TOKEN=${CI_TOKEN}
    - export MAIN_WORKFLOW_TOKEN=${MAIN_WORKFLOW_TOKEN}
    - cd /tmp/ && /usr/local/bin/start_and_wait_pipeline.sh

cleanup:
  only:
    - pushes
    - triggers
    - schedules
  stage: cleanup
  script:
    - rm /tmp/docker_build_${CI_PIPELINE_ID}.txt
