---
- hosts: localhost
  gather_facts: false
  pre_tasks:
    - include: tasks/env.yml action=load

  post_tasks:
    - include: tasks/env.yml action=save

  tasks:

    - include: tasks/group.yml
    - include: tasks/dump_ssh_key.yml
    - include: tasks/inventory.yml

    - set_fact:
        kubespray_values: "{{ kubespray.default }}"

    - set_fact:
        kubespray_values: "{{ kubespray_values | combine(kubespray.aws) }} "
      when: apocng_provision_driver == "terraform"

    - copy:
        content: "{{ kubespray_values | to_yaml }}"
        dest: "/tmp/{{ apocng_uuid }}-kubespray-values"
