---
- hosts: localhost
  gather_facts: false

  pre_tasks:
    - include: tasks/env.yml action=load

  post_tasks:
    - include: tasks/env.yml action=save

  tasks:
    - include: tasks/group.yml
    - include: tasks/dump_ssh_key.yml
#    - name: ping master host
#      ping:
#      register: master_ping
#      ignore_errors: true
#      delegate_to: "{{ groups['target_hosts'][0] }}"

    - name: "delete helm chart"
      command: "helm delete k8spray"
      delegate_to: "{{ groups['target_hosts'][0] }}"
      ignore_errors: true
      when: apocng_provision_driver != "manual"

    - include: tasks/terraform.yml
      when: apocng_provision_driver  == "terraform"

    - name: terraform destroy
      command: terraform destroy -force
      args:
        chdir: "{{ terraform_dir }}"
      when: apocng_provision_driver  == "terraform"

