---
- hosts: localhost
  gather_facts: false
  vars:
    work_dir: /opt/terraform

  pre_tasks:
    - include: tasks/env.yml action=load

  post_tasks:
    - include: tasks/env.yml action=save

  tasks:
    - include: tasks/group.yml terraform_item="{{ item }}"
      with_dict: "{{ apocng_terraform.modules[0].resources }}"
      when: apocng_provision_driver  == "terraform"

    - include: tasks/dump_ssh_key.yml

    - name: "delete helm chart"
      command: "helm delete k8spray"
      delegate_to: "{{ groups['target_hosts'][0] }}"

    - name: create terraform directory
      file:
        dest: "{{ work_dir }}"
        state: directory

    - name: template terraform manifest
      template:
        src: templates/terraform.tf.j2
        dest: "{{ work_dir }}/terraform.tf"

    - include: tasks/dump_ssh_key.yml

    - name: dump terraform state
      copy:
        content: "{{ apocng_terraform | to_json }}"
        dest: "{{ work_dir }}/terraform.tfstate"

    - name: json fix
      replace:
        path:  "/{{ work_dir }}/terraform.tfstate"
        regexp: '"(depends_on|deposed)": {}'
        replace: '"\1": []'

    - name: terraform init
      command: terraform init
      args:
        chdir: "{{ work_dir }}"

    - name: terraform plan
      command: terraform plan
      args:
        chdir: "{{ work_dir }}"

    - name: terraform destroy
      command: terraform destroy -force
      args:
        chdir: "{{ work_dir }}"
