---
- hosts: localhost
  gather_facts: false

  pre_tasks:
    - include: tasks/env.yml action=load
      tags:
        - env

  post_tasks:
    - include: tasks/env.yml action=save
      tags:
        - env

  tasks:

    - name: hello world
      command: "echo hello world"
