---
- hosts: localhost
  gather_facts: false
  vars:
    work_dir: /opt/terraform
    apocng_provision_driver: "terraform"

  pre_tasks:
    - include: tasks/env.yml action=load
      tags:
        - env

  post_tasks:
    - include: tasks/env.yml action=save
      tags:
        - env

  tasks:
    - include: tasks/group.yml terraform_item="{{ item }}"
      with_dict: "{{ apocng_terraform.modules[0].resources }}"
      when: apocng_provision_driver  == "terraform"

    - include: tasks/dump_ssh_key.yml

- hosts: target_hosts
  gather_facts: false
  tasks:
    - name: add python
      raw: "apt update && apt install -y python"

    - name: add python
      command: "id"

#    - name: prepare master
#      include: tasks/configure_master.yml
#      when: "inventory_hostname == groups['target_hosts'][0]"
