---
- hosts: localhost
  gather_facts: false
  vars:
    work_dir: /opt/terraform
    apocng_provision_driver: "terraform"

  pre_tasks:
    - include: tasks/env.yml action=load

  post_tasks:
    - include: tasks/env.yml action=save

  tasks:
    - include: tasks/group.yml terraform_item="{{ item }}"
      with_dict: "{{ apocng_terraform.modules[0].resources }}"
      when: apocng_provision_driver  == "terraform"

    - include: tasks/wait_for_ssh.yml wait_for_host="{{ item }}" wait_for_delay=0
      with_items: "{{ groups['target_hosts']|map('extract', hostvars, 'inventory_hostname') | list }}"

    - include: tasks/dump_ssh_key.yml

- hosts: target_hosts
  gather_facts: false
  tasks:

    - include: tasks/k8s_dependencies.yml
