---
- hosts: localhost
  gather_facts: false

  pre_tasks:
    - include: tasks/env.yml action=load

  post_tasks:
    - include: tasks/env.yml action=save

  tasks:
    - include: tasks/dump_ssh_key.yml

    - include: tasks/terraform.yml

    - name: terraform apply
      command: terraform apply
      args:
        chdir: "{{ work_dir }}"


    - name: load terraform facts
      include_vars:
        file: "{{ work_dir }}/terraform.tfstate"
        name: apocng_terraform
