---
- hosts: localhost
  gather_facts: false
  vars:
    terraform_dir: /opt/terraform

  pre_tasks:
    - include: tasks/env.yml action=load

  post_tasks:
    - include: tasks/env.yml action=save


  tasks:
    - include: tasks/group.yml
    - include: tasks/dump_ssh_key.yml
    - include: tasks/inventory.yml
