- name: dump inventory
  copy:
    content: "{{ apocng_kubespray_inventory }}"
    dest: "/tmp/inventory.cfg"
  when: apocng_kubespray_inventory is defined

- command: "python /opt/playbooks/kubespray/contrib/inventory_builder/inventory.py {{ groups['target_hosts']|map('extract', hostvars, 'inventory_hostname') | list | join(' ') }}"
  environment:
    CONFIG_FILE: /tmp/inventory.cfg

- name: save inventory
  set_fact:
    apocng_kubespray_inventory: "{{ lookup('file', '/tmp/inventory.cfg') }}"

- raw: "cat /tmp/inventory.cfg | awk '/^node[0-9]+?.*[^ ]$/ { printf(\"s,%s,%s,g\\n\", $1, $1 \" \" $2 \" \" $3) }' | sed -i'' -rf - /tmp/inventory.cfg"

- name: replace 1
  replace:
    path:  /tmp/inventory.cfg
    regexp: "^node[0-9]+?[ \t]+?ansible_host={{ item }}"
    replace: "{{ hostvars[item].aws.private_dns }} ansible_host={{ item }}"
  with_items: "{{ groups['target_hosts'] }}"

- name: replace 3
  replace:
    path:  /tmp/inventory.cfg
    regexp: "ip={{ item }}"
    replace: "access_ip={{ hostvars[item].aws.private_ip }} ansible_user=ubuntu become=true ansible_ssh_private_key_file=/tmp/{{ apocng_uuid }}-key"
  with_items: "{{ groups['target_hosts'] }}"
